<?php

/**
 * @file
 * Primary module hooks for Recipes module.
 */

/**
 * Implements hook_theme().
 */
function recipes_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ingredient__default' => [
      'base hook' => 'paragraph',
      'path' => $path . '/templates',
    ],
    'node__recipe__full' => [
      'base hook' => 'node',
      'path' => $path . '/templates',
    ],
    'field__node__field_paragraphs__recipe' => [
      'base hook' => 'field',
      'path' => $path . '/templates',
    ],
  ];
}
