name: cf
recipe: drupal10

env_file:
  - lando/defaults.env

config:
  composer_version: 2-latest
  database: mysql:8.0.32
  php: 8.3
  webroot: web
  config:
    php: lando/config/php.ini
    mysql: lando/config/my.cnf
    database: lando/config/custom.cnf
  xdebug: true

excludes:
  - node_modules

proxy:
#  search:
#    - search.tf.lndo.site
  pma:
    - db.cf.lndo.site
  mailhog:
    - mail.cf.lndo.site
  search:
    - search.cf.lndo.site

services:
#  search:
#    type: elasticsearch:7.17.18
#    portforward: 9200
  pma:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    type: php:8.3
    build:
      - composer install
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://cf.lndo.site"
        # Allows path mapping in PhpStorm and CLI debugging.
        # https://docs.lando.dev/guides/lando-phpstorm.html#debugging-cli-commands.
        PHP_IDE_CONFIG: "serverName=tf"
        # Set debug mode here, instead of in config: xdebug so it can be toggled off and on.
        # Develop allows additional features, like html in var_dump.
        # https://xdebug.org/docs/develop.
        # Debug allows step debugging.
        # https://xdebug.org/docs/remote.
        XDEBUG_MODE: 'debug,develop'
        # Causes Xdebug to trigger on every request, no need to do XDEBUG_SESSION in the URL.
        XDEBUG_SESSION: 1
  node:
    type: 'node:22'
    globals:
      gulp-cli: latest
    scanner: false
    ssl: true
    sslExpose: false
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
  search:
    type: solr:9.4
    portforward: true
    core: collection1
    config:
      dir: .platform/solr-conf

tooling:
  bash:
    service: appserver
  composer:
    service: appserver
    description: run composer commands
    cmd: /usr/local/bin/composer
  drupal:
    service: appserver
    description: Runs Drupal console
    cmd: /app/vendor/bin/drupal
    user: www-data
  phpunit:
    service: appserver
    description: run PHPUnit- use lando phpunit
  node:
    service: node
  npm:
    service: node
  nvm:
    service: node
  gulp:
    service: node
  build:
    service: node
    description: Build theme assets.
    cmd: bash /app/lando/build_theme.sh
  xon:
    service: appserver
    description: Enable Xdebug.
    user: root
    cmd:
      - docker-php-ext-enable xdebug && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 2 && echo "Xdebug On" && tput sgr 0 && echo
  xoff:
    service: appserver
    description: Disable Xdebug.
    user: root
    cmd:
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 1 && echo "Xdebug Off" && tput sgr 0 && echo
