# TODO Fix PHPUnit testing of only custom themes/modules
# TODO Look into Portainer

name: cf
recipe: drupal9

env_file:
 - lando/defaults.env

config:
  composer_version: 2
  via: apache
  webroot: web
  xdebug: true
  config:
    php: lando/config/php.ini
    mysql: lando/config/my.cnf
    # This is done purely to fix an issue with mysql 8
    database: lando/my_custom.cnf

proxy:
  search:
    - search.cf.lndo.site
  pma:
    - db.cf.lndo.site
  mailhog:
    - mail.cf.lndo.site

services:
  search:
    type: solr:8.4
    portforward: true
    core: collection1
    config:
      dir: config/solr-conf
  database:
    type: mysql:8.0.32
  #    portforward: 3310
  pma:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    type: php:8.1
    composer:
      behat/behat: 3.3.1
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://cf.lndo.site"
    run_as_root:
#      - "apt-get install python3-pip"
#      - "pip3 install robin_stocks"
      - "bash /app/lando/scripts/build.sh"
  node:
    type: node:16
    globals:
      gulp-cli: latest
    build:
      - "cd $LANDO_MOUNT && npm install -y"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

tooling:
  composer:
    service: appserver
    description: run composer commands
    cmd: /usr/local/bin/composer
  drupal:
    service: appserver
    description: Runs Drupal console
    cmd: /app/vendor/bin/drupal
    user: www-data
  phpunit:
    service: appserver
    description: run PHPUnit- use lando phpunit
  behat:
    service: appserver
    description: run behat- use lando behat
    cmd: cd /app ; behat  # Run behat from the /app  directory
  node:
    service: node
  npm:
    service: node
  gulp:
    service: node
