version: 0.0
os: linux
files:
  - source: build.tar
    destination: /var/www/

hooks:
  BeforeInstall:
    - location: ~/scripts/aws/01_configure_instance.sh
    - location: scripts/aws/02_install_codebase.sh
    - location: scripts/aws/03_mount_files.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/aws/10_fix_permissions.sh
      timeout: 300
      runas: root
#  ApplicationStart:
#    - location: scripts/start_server.sh
#    - location: scripts/create_test_db.sh
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      timeout: 300
#      runas: root