version: 0.1

phases:
  pre_build:
    commands:
      - echo Pre-Build started
      - echo Installing gulp...
      - npm install --global gulp-cli
      - echo Pre-Build finished
  build:
    commands:
      - echo Build started
      - echo Running composer install to add contrib modules and ...
      - composer install
      - echo Running gulp...
      - gulp
      - echo Build finished
  post_build:
    commands:
      - echo Post-Build started
      - echo Post-Build finished
artifacts:
  files:
    - index.html
    - appspec.yml