ut_utilities.settings:
  type: config_object
  label: 'UT Utilities settings'
  mapping:
    default_areas_of_interest:
      type: sequence
      label: 'Default Areas of Interest'
      sequence:
        type: string
    allow_social_api_registration:
      type: boolean
      label: 'Allow Social API logins to complete registration'
