<?php
/**
 * @file
 *
 * Place your custom PHP code in this file.
 */

//christoph_preprocess_node($variables) {
//  ddl($variables, 'vars');
//}

//function christoph_preprocess(&$variables, $hook, $info) {
  //Bootstrap::preprocess($variables, $hook, $info);
//  ddl($variables, 'vars');
//  ddl($hook, 'hook');
//  ddl($info, 'info');
//}

function christoph_preprocess_field(&$variables, $hook) {
  $element = $variables['element'];
  if (isset($element['#field_name'])) {
    if ($element['#field_name'] == 'uid') {

      $variables['user_name'] = 'name!';
      $variables['user_photo'] = 'photo!';

     // dpm(array_keys($element['#items']));
    }
  }


}
