version: 0.1

phases:
  pre_build:
    commands:
      - echo Pre-Build started
      - echo Pre-Building...
      - echo Pre-Build finished
  build:
    commands:
      - echo Build started
      - echo Building...
      - cd aws && tar -zcvf build.tar appspec.yml
      - echo Build finished
  post_build:
    commands:
      - echo Post-Build started
      - echo Post-Building...
      - echo Post-Build finished
artifacts:
  files:
    - aws/build.tar
    - aws/appspec.yml