<?php

/**
 * @file
 * Contains unsettling_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function unsettling_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the unsettling_blocks module.
    case 'help.page.unsettling_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom blocks created by Unsettling Trend') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function unsettling_blocks_theme() {
  return [
    'unsettling_blocks' => [
      'render element' => 'children',
    ],
  ];
}
