<?php

/**
 * @file
 * Contains cnc_extras.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cnc_extras_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cnc_extras module.
    case 'help.page.cnc_extras':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extra things for the Chris &amp; Cammy website.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function cnc_extras_theme() {
  return [
    'cnc_extras' => [
      'render element' => 'children',
    ],
    'header_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
